# Generated by Django 3.1.2 on 2020-12-23 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='moblie',
            new_name='mobile',
        ),
    ]
